name: CI

on: [push, pull_request]

env:
  IMAGE_NAME: app-candidate
  VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build
        run: mvn -B -U -ntp clean compile

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Run Unit Tests
        run: mvn -B -U -ntp test

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Run Integration Tests
        run: mvn -B -U -ntp verify

  acceptance:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@v4

      # Construir imagen Docker del candidato
      - name: Build candidate image
        run: docker build -t $IMAGE_NAME:$VERSION .

      # Simular despliegue Blue (8080)
      - name: Run BLUE (stable) on 8080
        run: docker run -d -p 8080:8080 --name blue $IMAGE_NAME:$VERSION || true

      # Simular despliegue Green (8081)
      - name: Run GREEN (candidate) on 8081
        run: docker run -d -p 8081:8080 --name green $IMAGE_NAME:$VERSION

      # Probar el contenedor Green
      - name: Acceptance tests against GREEN
        run: |
          echo "Probando entorno GREEN..."
          sleep 5
          curl --fail http://localhost:8081 || exit 1
