name: CD - Deploy a Test (Blue/Green + Rollback)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build app
        run: mvn -B -U -ntp clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      - name: Save candidate tag
        id: meta
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  acceptance:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target
      - name: Build candidate image
        run: docker build -t app-candidate:${{ needs.build-and-package.outputs.short_sha }} .
      - name: Run BLUE (stable) on 8080
        run: docker run -d --name blue -p 8080:8080 app-candidate:${{ needs.build-and-package.outputs.short_sha }} || true
      - name: Run GREEN (candidate) on 8081
        run: docker run -d --name green -p 8081:8080 app-candidate:${{ needs.build-and-package.outputs.short_sha }}
      - name: Acceptance tests against GREEN
        run: curl --fail http://localhost:8081 || exit 1

  promote-or-rollback:
    runs-on: ubuntu-latest
    needs: acceptance
    if: always()
    steps:
      - name: Promote if GREEN passed
        if: success()
        run: |
          echo "✅ Promoviendo GREEN -> BLUE"
          docker stop blue || true
          docker rm blue || true
          docker rename green blue
      - name: Rollback if GREEN failed
        if: failure()
        run: |
          echo "⛔ GREEN falló, rollback al BLUE estable"
          docker stop green || true
          docker rm green || true
