name: CD - Deploy a Test (Blue/Green + Rollback)

on:
  workflow_dispatch:
  push:
    branches: [ main ]  

env:
  IMAGE_NAME: app-candidate
  VERSION: ${{ github.sha }}

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build app
        run: mvn -B -U -ntp clean package -DskipTests

      - name: Build candidate image
        run: |
          docker build \
            -t $IMAGE_NAME:$VERSION \
            --build-arg APP_VERSION="${VERSION}" \
            -f deploy/Dockerfile deploy

  acceptance:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - uses: actions/checkout@v4
      - name: Build candidate image again
        run: docker build -t $IMAGE_NAME:$VERSION -f deploy/Dockerfile deploy

      - name: Run BLUE (stable) on 8080
        run: docker run -d --name blue -p 8080:8080 $IMAGE_NAME:$VERSION || true

      - name: Run GREEN (candidate) on 8081
        run: docker run -d --name green -p 8081:8080 $IMAGE_NAME:$VERSION

      - name: Acceptance tests against GREEN
        run: |
          echo "Probando entorno GREEN..."
          sleep 5
          curl --fail http://localhost:8081 || exit 1

  promote-or-rollback:
    runs-on: ubuntu-latest
    needs: acceptance
    if: always()
    steps:
      - name: Promote if GREEN passed
        if: success()
        run: |
          echo "✅ GREEN pasó pruebas, promoviendo a producción (8080)..."
          docker stop blue || true
          docker rm blue || true
          docker rename green blue
          echo "Promoción completada."

      - name: Rollback if GREEN failed
        if: failure()
        run: |
          echo "⚠️ GREEN falló, rollback al BLUE estable"
          docker stop green || true
          docker rm green || true
